Update ScientificCalculator
MaiNgo95/Calculator_Bonus pull request #1
Opened 2022-11-19 20:32 UTC by Sjan00

Added frame and buttons

2022-11-20 14:31 UTC, MaiNgo95 commented
The method addActionListener(ActionListener) in the type AbstractButton is not applicable to the arguments (ScientificCalculator).

2022-11-20 14:36 UTC, MaiNgo95 requested changes
Please add the java file. Need to improve by adding "implements ActionListener."

2022-11-20 15:51 UTC, Sjan00 commented
I have updated the file, I added "implements ActionListener"
I've also updated line 22, from 
     frame = new JFrame("Calculator") to frame = new JFrame("Scientific Calculator")

2022-11-22 02:27 UTC, MaiNgo95 approved these changes

2022-11-22 02:50 UTC, merged